#!/bin/sh

#Pull in souplist.txt file
. /var/www/html/souplist.txt

#What are the soup values?
#echo $soup1
#echo $soup2
#echo $soup3

cp -f /var/www/html/indexsoups3newsoup-GOLD.html /var/www/html/indexsoups3newsoup-GOLD.html-tmp

sed -i "s/soup1/$soup1/g" /var/www/html/indexsoups3newsoup-GOLD.html
sed -i "s/soup2/$soup2/g" /var/www/html/indexsoups3newsoup-GOLD.html
sed -i "s/soup3/$soup3/g" /var/www/html/indexsoups3newsoup-GOLD.html
#sed -i "s/soup4/$soup4/g" /var/www/html/indexsoups3newsoup-GOLD.html

mv -f /var/www/html/indexsoups3newsoup-GOLD.html /var/www/html/indexsoups3newsoup.html
mv -f /var/www/html/indexsoups3newsoup-GOLD.html-tmp /var/www/html/indexsoups3newsoup-GOLD.html

rm /home/viewtouch/Media/menu1/*
wkhtmltoimage --disable-smart-width --width 1080 --height 1920 http://localhost/indexsoups3newsoup.html /home/viewtouch/Media/menu1/CL023new.jpg
/home/viewtouch/bin/restart_x
